# Generated by Django 6.0.6 on 2026-06-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_author_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='products.book'),
        ),
    ]
